version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      tags:
        - server:latest
    ports:
      - "4000:4000"
    networks:
      - filevault_network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      tags:
        - client:latest
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - filevault_network

  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins:/var/jenkins_home/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - server
      - client
    networks:
      - filevault_network

volumes:
  jenkins_home:

networks:
  filevault_network:
    driver: bridge
